# Generated by Django 5.0.6 on 2024-06-29 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Contact_us',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Social_media',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.RenameField(
            model_name='redikt',
            old_name='work_place_en',
            new_name='description_place_en',
        ),
        migrations.RenameField(
            model_name='redikt',
            old_name='work_place_ru',
            new_name='description_place_ru',
        ),
        migrations.RenameField(
            model_name='redikt',
            old_name='work_place_uz',
            new_name='description_place_uz',
        ),
        migrations.RemoveField(
            model_name='redikt',
            name='discription',
        ),
        migrations.AddField(
            model_name='redikt',
            name='image',
            field=models.ImageField(default=1, upload_to='editors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.category'),
        ),
    ]
